services:
  db:
    image: mysql:8.0
    container_name: db_go_vue
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
        - 3306:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
